<?php

session_start();
include "cores/connect.php";

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/styleadm.css">
    <link rel="stylesheet" href="css/reset.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Advent+Pro:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <title>Admin</title>
</head>
<body>
    <h2 class="title-admin-panel">Admin Panel</h2>
    <div class="container-signin-admin">
        <div class="container-signin-admin-inner">
          <h3 class="title-signin">Вход</h3>
          <form action="handler/authAdm.php" method="post">
            <div class="form-group">
                <input required type="text" class="form-control" name="loginAdmin" id="" placeholder="Логин">
              </div>
              <div class="form-group">
                <input required type="password" class="form-control" name="passAdmin" id="" placeholder="Пароль">
              </div>
              <button type="submit" class="btn btn-primary">Войти</button>
          </form>
        </div>
      </div>
      
</body>
</html>